name: "Contribution Agreement"
on:
  pull_request_target:
    types: [opened,synchronize]

jobs:
  AgreementCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - run: |
          echo Checking contribution agreement for $USER
          tail -n +36 Contribution\ Agreement.md
          tail -n +36 Contribution\ Agreement.md | awk -F\| '{print $3}' | grep -w $USER
        env:
          USER: ${{ github.actor }}

